name: Java
on: [push]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build 
        run: ./gradlew build
        
      - name : Run
        run: java -jar build/libs/*.jar 3 1
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: MonArtifact
          path: build/libs/*.jar
      
      
